### ISSUE TITLE
upgrade to leveldown 1.0

### ISSUE THREAD

**Issue by maxogden** [mafintosh/leveldown-prebuilt#2]
https://github.com/rvagg/node-leveldown/commit/185b870402ac57a1f3c939841ff8021a666ffcb6

i'm not sure what the 1.0 changes were, but we should probably re-compile the prebuilt stuff now

todo:

- [x] leveldown-v1.0.1-node-v43-darwin-x64.tar.gz 
- [x] leveldown-v1.0.1-node-v43-linux-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v43-linux-x64.tar.gz
- [x] leveldown-v1.0.1-node-v43-win32-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v43-win32-x64.tar.gz
- [x] leveldown-v1.0.1-node-v14-darwin-x64.tar.gz 
- [x] leveldown-v1.0.1-node-v14-linux-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v14-linux-x64.tar.gz
- [x] leveldown-v1.0.1-node-v14-win32-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v14-win32-x64.tar.gz
- [x] leveldown-v1.0.1-node-v11-darwin-x64.tar.gz 
- [x] leveldown-v1.0.1-node-v11-linux-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v11-linux-x64.tar.gz
- [x] leveldown-v1.0.1-node-v11-win32-ia32.tar.gz
- [x] leveldown-v1.0.1-node-v11-win32-x64.tar.gz

**Comment by mafintosh** [comment]
Out in 1.0.3
